SOURCES = parse/span.mli \
    parse/span.ml \
    parse/util.ml \
    parse/lexer.mll \
    parse/ast.ml \
    parse/parser.mly \
    sema/sema.ml \
    sema/typecanon.mli \
    sema/finitetypecheck.mli \
    sema/typecanon.ml \
    sema/finitetypecheck.ml \
    sema/typecheck.ml \
    middle/trans.ml \
    middle/lowering.ml \
    middle/canontrans.ml \
    middle/instcombine.ml \
    middle/mips/mipsframe.ml \
    middle/backend.ml \
    middle/mipsisel.ml \
    main.ml
RESULT = sporkc

include OCamlMakefile